version: "3.8"
services:
  frontend:
    build:
      context: ./shop-frontend
      dockerfile: ./Dockerfile
    ports:
      - "3001:3000"
    environment:
      - VITE_API_SERVER_URL=http://localhost:8085/api
    depends_on:
      - backend

  backend:
    build:
      context: ./shop-backend
      dockerfile: ./Dockerfile
    ports:
      - "8085:8085"
      - "27017:27017"

    environment:
      - PORT=8085
      - CLIENT_URL=http://localhost:3000
      - AWS_BUCKET_NAME=devops-static-resources
      - AWS_REGION=us-east-1
